/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var s=b.document,z=b.navigator,B="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),H=!1,t=0,u=[],l=[],g=[],h={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},f=[],C={},I=0,J=[],D=null,X={},y={},ia=null,w,Y=[].slice,ja,Z,O,q,E,$,P,ka,la,ma,K,aa,Q,R,na,L,oa,pa,qa,ra,r,sa,F,S,ta,ba,ua,va,ca,v,wa,da,T,U,xa,ya,V,za,ea,fa,Aa,ga,G,M,N,W,ha,x=function(a){try{return{init:R,hash:Q,rules:xa,hasRules:V,defaults:Aa,__qc:function(){return!0}}[a].apply(null,Y.call(arguments,1))}catch(c){return!1}};x.evts=0;x.v=2;x.SD=B;x.qpixelsent=[];U=function(a){var c=a?a.length||
0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};fa=function(a){(a=a||b._qacct)&&(ca(f,a)||f.push(a))};ca=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};da=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};T=function(a){var c,d;c=da(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};V=function(a){return ca(g,a)};Aa=function(a,c){var d;a&&((d=X[a])&&(c=
W(c,d)),c.qacct&&delete c.qacct,X[a]=c)};ga=function(a){var c,d;if(q(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?r(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=y[d])?W(c,a):a,y[d]=c);fa(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ga(a[c])};W=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||
"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ba(d,a,c);ba(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ba=function(a,c,d){var b,m,A,g,f,n;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(m=c[b],A=d[b],g="",f=!!m&&"string"==typeof m,n=!!A&&"string"==typeof A,f&&(g=m),f&&n&&(g+=","),n&&(g+=A),a[b]=g)};G=function(){var a=[],c,d;if(!(0<I)){wa();for(c in y)y.hasOwnProperty(c)&&y[c]&&(d=y[c],a.push(d),delete y[c]);1==a.length&&r(a[0]);1<a.length&&
r(a)}};M=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],h.hasOwnProperty(b.substring(2))?C[b]=5:V(b)||c.push(b);if(0===c.length)G();else for(d=0;d<c.length;d++)b=c[d],g.push(b),ua(b)};va=function(){for(var a;J[0]&&("loaded"==J[0].readyState||"complete"==J[0].readyState);)a=J.shift(),a.onreadystatechange=null,D.parentNode.insertBefore(a,D),N()};ua=function(a){var c,d;c=("https:"===s.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";D=D||s.scripts[0];I++;d=s.createElement("script");
"async"in d?(d.src=c,d.async=!1,d.onload=function(){C[a]=0;N()},d.onerror=function(){C[a]=1;N()},D.parentNode.insertBefore(d,D)):d.readyState?(C[a]=2,J.push(d),d.onreadystatechange=va,d.src=c):(C[a]=4,N())};N=function(){I-=0<I?1:0;G()};xa=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ga(c):r(c,!0)};for(c=0;c<arguments.length;c++)d=Y.call(arguments[c],0),d.splice(1,0,b),ya.apply(null,d);a=!1;H&&G()}};ya=function(a,c){var d=[],b=[],m=c||r,A,f,h,n,p;if((A=Y.call(arguments,2))&&A.length){f=
A[0]||U;h=A[1];n=A[2];A=n.length;for(p=0;p<A;p++)d.push(!1),b.push(null);d={p:a,f:d,r:f,c:n,a:h,v:b};V(a)||g.push(a);l.push(d);za(d,m)}};za=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(b){var d,e;try{d=a.c[b][0],e=a.c[b].slice(1),e.splice(0,0,function(d){a.f[b]=!0;a.v[b]=d;ea(a,c)}),d.apply(null,e)}catch(g){a.f[b]=!0,a.v[b]=!1,ea(a,c)}})(b)};ea=function(a,c){var b=a.a,e=a.v,m=a.r||U,g,f,h,n,p,k;(g=U(a.f))&&(g=g&&m(e));if(g)for(e=0;e<b.length;e++)try{f=b[e][0];h=1<b[e].length?
b[e].slice(1):[];h=h.concat(a.v);n=f.apply(null,h);p={qacct:a.p,event:"rule"};for(k in n)n.hasOwnProperty(k)&&"qacct"!==k&&(p[k]=n[k]);c(p)}catch(q){}};ja=function(){return Z(0)!==Z(6)?1:0};Z=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};O=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};E="function"===typeof encodeURIComponent?encodeURIComponent:O;q=function(a){return"undefined"!=typeof a&&null!=a};$=function(){return Math.round(2147483647*
Math.random())};P=function(a){var c="",b=s.cookie,e;if(!b)return c;e=b.indexOf(a+"\x3d");a=e+a.length+1;-1<e&&(c=b.indexOf(";",a),0>c&&(c=b.length),c=b.substring(a,c));return c};ka=function(){var a="",c=K(),b,e,m;if(1===t)return";fpan\x3du;fpa\x3d";b=Q(c);for(e=0;e<B.length;e++)if(B[e]===b)return";fpan\x3du;fpa\x3d";b=new Date;e=P("__qca");if(0<e.length){try{m=+e.split("-")[2],338688E5<b-m&&(s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(m+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(g){}a+=
";fpan\x3d0;fpa\x3d"+e}0===P("__qca").length&&(e="P0-"+$()+"-"+b.getTime(),s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),e=P("__qca"),a=0<e.length?a+(";fpan\x3d1;fpa\x3d"+e):a+";fpan\x3du;fpa\x3d");return a};la=function(a){s.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+K()};K=function(){var a,c,b,e;a=s.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");e=c.length;
if(3>e)return a;b=c[e-1];return 3>b.length?a:a=c[e-2]+"."+b};aa=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};Q=function(a){var c;c=aa(2166136261,a);a=aa(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};S=function(a,c,d){var e="",m=b._qacct,g=null,f="webpage",h="load",n={},p,k,m=c?c.qacct||b._qacct:b._qacct;p=y[m];c?p&&(c=W(c,p)):c=p;m&&delete y[m];if(null!=c)for(k in c)n[k]=!0,c.hasOwnProperty(k)&&"string"===typeof k&&
"string"===typeof c[k]&&("uid"===k||"uh"===k?(na()||(g=Q(c[k])),delete c[k]):"qacct"!==k&&(0<c[k].length?e+=";"+k+a+"\x3d"+E(c[k]):n[k]=!1,"media"===k&&(f=c[k]),"event"===k&&(h=c[k])));if("string"!==typeof m){if(!q(b._qacct)||0===b._qacct.length)return"";m=b._qacct}if(m&&(p=X[m]))for(k in p)"string"===typeof k&&p.hasOwnProperty(k)&&!n[k]&&(e+=";"+k+a+"\x3d"+E(p[k]),"media"===k&&(f=p[k]),"event"===k&&(h=p[k]));n=C[m];q(n)||(n=3);e+=";rf"+a+"\x3d"+n;"string"===typeof g&&(c.uh=g,e+=";uh"+a+"\x3d"+E(g));
if("webpage"===f&&"load"===h){for(c=0;c<x.qpixelsent.length;c++)if(x.qpixelsent[c]===m&&!d)return"";x.qpixelsent.push(m)}"ad"===f&&(t=1);return";a"+a+"\x3d"+m+e};ta=function(){var a=s.getElementsByTagName("meta"),c="",b,e,g,f;for(b=0;b<a.length;b++){g=a[b];if(1E3<=c.length)return c;q(g)&&q(g.attributes)&&q(g.attributes.property)&&q(g.attributes.property.value)&&q(g.content)&&(e=g.attributes.property.value,g=g.content,3<e.length&&"og:"===e.substring(0,3)&&(0<c.length&&(c+=","),f=80<g.length?80:g.length,
c+=O(e.substring(3,e.length))+"."+O(g.substring(0,f))))}return E(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;q(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};r=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",g=$(),f="",h="",l="",C="",n="",
p="u",k="1",v=0,w=[],r,y,B,D;t=0;q(x.qpixelsent)||(x.qpixelsent=[]);if(q(a))for(r in a)if("string"==typeof a[r]){h=S("",a,c);break}else"object"==typeof a[r]&&null!=a[r]&&(++v,h+=S("."+v,a[r],c));else"string"===typeof _qacct&&(h=S("",null,c));0!==h.length&&(v=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(p=z.javaEnabled()?"1":"0"),q(b._qmeta)&&(l=";m\x3d"+E(b._qmeta),b._qmeta=null),self.screen&&(f=screen.width+"x"+screen.height+"x"+screen.colorDepth),y=new Date,B=ja(),D=ka(),b.location&&
b.location.href&&(C=E(b.location.href)),s&&s.referrer&&(n=E(s.referrer)),b.self===b.top&&(k="0"),r=ta(),w.push("/pixel;r\x3d"+g+h+D+";ns\x3d"+k+";ce\x3d"+v),w.push(";je\x3d"+p+";sr\x3d"+f+";enc\x3d"+d+";dst\x3d"+B+";et\x3d"+y.getTime()+";tzo\x3d"+y.getTimezoneOffset()+l+";ref\x3d"+n+";url\x3d"+C+";ogl\x3d"+r),u.push(w),F())};sa=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",oa(w)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(w),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&la("__qca")}};F=function(){if(w)for(;u.length;)sa(u.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||q(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!q(w)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}w=1}F()};pa=function(a,c){w=PrivacyManagerAPI.callApi(a,"quantserve.com",
K(),"truste.com",c);F()};qa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:K(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",L,!1);else if(b.attachEvent)b.attachEvent("onmessage",L);else{w=!0;F();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(g){}ia=setTimeout(function(){q(w)||(w=!0,F())},25)};L=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",L,!1):b.detachEvent&&window.detachEvent("onmessage",L),w=c.PrivacyManagerAPI,F())}};ha=function(){var a=arguments,c,b;v([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],r(c);f.length?M(f.slice(0)):G()};v=function(a){var c=da(a);if("array"===c)for(c=0;c<a.length;c++)v(a[c]);else"object"===c&&fa(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||
r({qacct:b._qacct});if(!x.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&r(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&r(b.ezt[a]);b._qevents={push:ha};b.ezt.push=function(){var a=arguments,d;if(q(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ha.apply(this,arguments)};x.evts=1}};R=function(){var a;q(b._qevents)||(b._qevents=[]);q(b.ezt)||(b.ezt=[]);b._qoptions&&(a=T(b._qoptions),v(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=T(b.qcdata),
v(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=T(b.smarttagdata),v(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);x.evts||(b._qevents.push=function(){v([].slice.call(arguments));M(f.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){v([].slice.call(arguments));M(f.slice(0));return[].push.apply(b.ezt,arguments)});v(b.ezt);v(b._qevents);v({qacct:b._qacct});b._qoptions=null;f.length?M(f.slice(0)):G();H=!0};b.quantserve=b.quantserve||R;x.quantserve=R;
return x}(window);
try{__qc("hasRules","p-D1yc5zQgjmqr5")||function(b,s,z){var B=function(b,h,f){return b?"nc"===b?!h||!f||0>h.indexOf(f):"eq"===b?h===f:"sw"===b?0===h.indexOf(f):"ew"===b?(b=h.length-f.length,h=h.lastIndexOf(f,b),-1!==h&&h===b):"c"===b?0<=h.indexOf(f):!1:!1},H=function(b){var h=z.createElement("a");h.href=b;return h},t=function(b,h,f){var l;l=s.top===s.self?z.location.host:H(z.referrer).hostname;B(h,l,f)?b(l):b(!1)},u=function(b,h,f){var l;l=s.top===s.self?z.location.pathname:H(z.referrer).pathname;B(h,
l,f)?b(l):b(!1)},l=function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[l,"Money.Tech.Powering Your World"]],[[t,"eq","money.cnn.com"],[u,"c","/powering-your-world"]]],[b,null,[[l,"Money.Luxury"]],[[u,"sw","/luxury"],[t,"eq","money.cnn.com"]]],[b,null,[[l,"Money.Tech.Innovation Nation"]],[[t,"eq","money.cnn.com"],[u,"c","/technology"],[u,"c","/innovationnation"]]],[b,null,[[l,"Money.Media"]],[[u,"sw","/media"],
[t,"eq","money.cnn.com"]]],[b,null,[[l,"Money.Tech"]],[[u,"sw","/technology"],[t,"eq","money.cnn.com"]]],[b,null,[[l,"Money.Markets"]],[[t,"eq","money.cnn.com"],[u,"sw","/data"]]],[b,null,[[l,"Money.Business"]],[[u,"c","/news"],[t,"eq","money.cnn.com"]]],[b,null,[[l,"Money.International"]],[[t,"eq","money.cnn.com"],[u,"c","/international"]]],[b,null,[[l,"Money.Markets"]],[[u,"c","/markets"],[t,"eq","money.cnn.com"]]],[b,null,[[l,"International.Arabic"]],[[t,"eq","arabic.cnn.com"]]],[b,null,[[l,"International.Espanol"]],
[[t,"eq","cnnespanol.cnn.com"]]],[b,null,[[l,"Money.Upstarts"]],[[t,"eq","money.cnn.com"],[u,"c","/upstarts"]]],[b,null,[[l,"Money.India"]],[[t,"eq","money.cnn.com"],[u,"c","/news"],[u,"c","/india"]]])}("p-D1yc5zQgjmqr5",window,document)}catch(nfe$$3){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$4){};